### ISSUE TITLE
Manual GitHub Action for Cloudflare Pages

### ISSUE THREAD

**Issue by Triloworld** [crgeary/wp-jamstack-deployments#52]
Pleas include this example for all oAuth apps that work only by pushing on main branch

Require: GITHUB_TOKEN (Login and goto https://github.com/settings/tokens)

In WP:
```php
function jamstack_deployments_webhook_request_args_callback( $args ) {
    
	$args['headers'] = array(
	  'Authorization' => 'token GITHUB_TOKEN',
	);
	
	$args['body'] = '{"event_type": "externall-deploy", "client_payload": {}}';

    return $args;
}
add_filter( 'jamstack_deployments_webhook_request_args', 'jamstack_deployments_webhook_request_args_callback' );
```

In Github Action Workflow:
```yml
name: Public workflow

on:
  repository_dispatch:
    types: [externall-deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Push to Cloudflare" -a --allow-empty
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
```
